### ISSUE TITLE
Has this work published?

### ISSUE THREAD

**Issue by WangXinyan940** [scychon/openmm_drudeNose#2]
After reading your code, I have to say it's a great work. Has this work published?

**Comment by scychon** [comment]
Thanks for your interest !
We're in the final round of our manuscript, and think we'll submit this work within a couple of weeks. The github page will be updated as soon as the work is published.

**Comment by scychon** [comment]
The paper just got accepted in J. Phys. Chem. Lett., [link here](https://pubs.acs.org/doi/10.1021/acs.jpclett.9b02983). Please check out the paper if interested, and also please cite it if you use it in your own work !
